### ISSUE TITLE
Use the engine_version_semver key when dealing with artifacts configuration

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/falcoctl#348]
**What would you like to be added**:

The falcosecurity/falco#2899 PR introduces a new key in the `/versions` endpoint exposed by falcoctl. We need to use the new key instead of the `engine_version` key. 

We also need to write extensive unit/integration tests to make sure that we do not break existing deployments of falco when upgrading the artifacts to newer versions.

**Comment by loresuso** [comment]
With the introduction of the new key in both Falco and new (to be released) packages, falcoctl was not modified, since it already could handle numeric and semver versions. The PR by @FedeDP adds a test on the specific way we always checked for requirements, and I believe it is enough on the unit test side.
If we want to do bigger integration tests, I am not sure we should do that in falcoctl since we want to test if we are not breaking Falco.
